ecommerce/common/urls.py
from django.urls import path

from .import views

app_name='common'

urlpatterns = [
    path('',views.home,name='home'),
    path('about',views.about,name='about'),
    path('readytofry',views.readytofry,name='readytofry'),
    path('readytocook',views.readytocook,name='readytocook'),
    path('heatandeat',views.heatandeat,name='heatandeat'),
    path('contact',views.contact,name='contact'),
    path('shop',views.shop,name='shop'),
    path('login',views.login,name='login'),
    path('signup',views.signup,name='signup'),
    path('cart',views.cart,name='cart'),

    path('changepassword',views.change_password,name='change_password'),
    path('product/<int:pid>',views.product_detailes,name='product_detailes'),
    path('logout',views.logout,name='logout'),
    path('order_details',views.order_details,name='order_details'),
    path('payment',views.payment,name='payment'),

    path('mycart/remove/<int:c_id>',views.removecart,name='remove_cart'),
    path('change_qty',views.change_qty,name="change_qty"),
    path("order_payment", views.order_payment, name="orderpayment"),
    path("updatepayment", views.updatepayment, name="updatepayment"),
    path("profile", views.profile, name="profile"),
    path("edit_profile", views.edit_profile, name="edit_profile"),
    path("my_orders", views.my_orders, name="my_orders"),
    path("my_orders/cancel_order/<int:o_id>", views.cancel_order, name="cancel_order"),
    path("search_product", views.search_product, name="search_product"),

















    
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings







urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('adminsite/',include('ecommerceadmin.urls')),

    
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce/common/models.py
from django.db import models
from ecommerceadmin.models import Products
from datetime import date

# Create your models here.


class Customer(models.Model):
    customer_name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    phone = models.BigIntegerField()
    password = models.CharField(max_length=10)
    address = models.CharField(max_length=100,default='')

    class Meta:
        db_table = 'customer'

class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    qty = models.IntegerField(default=0)

    
    class Meta:
        db_table = 'cart'


class Order(models.Model):
    customer =models.ForeignKey(Customer,on_delete=models.CASCADE)
    amount = models.FloatField()
    status = models.CharField(max_length=20,default="pending")
    provider_order_id = models.CharField(max_length=40)
    payment_id = models.CharField(max_length=36)
    signature_id = models.CharField(max_length=128)

    class Meta:
        db_table = 'order_tb'



class Order_detail(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    productid = models.ForeignKey(Products,on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=20,default="pending") #update after payment confirmed
    payment_type = models.CharField(max_length=20)
    order=models.ForeignKey(Order,on_delete=models.CASCADE)


    class Meta:
        db_table = 'order_detail'


class Review(models.Model):
    name = models.CharField(max_length=50,default='')
    
    email = models.CharField(max_length=50)
    review = models.CharField(max_length=150)



    
    class Meta:
        db_table = 'review'
    

ecommerce/common/views.py
from django.shortcuts import render,redirect
from .models import Customer , Cart , Order , Order_detail,Review
from ecommerceadmin.models import Products
from .decorators import login_required
from django.http import JsonResponse
from django.db.models import F,Q,Sum
import razorpay
from django.core import serializers
from django.conf import settings
from . serializer import productSerialize



# Create your views here.

def home(request):

    product =Products.objects.all()[0:4]

    return render(request,'common/home.html',{'products':product})

def about(request):
    return render(request,('common/about.html'))

def readytofry(request):
    return render(request,('common/readytofry.html'))

def readytocook(request):
    return render(request,('common/readytocook.html'))

def heatandeat(request):
    return render(request,('common/heatandeat.html'))

def contact(request):

    if request.method == "POST":



        name = request.POST['name']
        email = request.POST['email']
        review = request.POST['review']




        reviews = Review(name = name , email = email , review = review )
        reviews.save()



    return render(request,'common/contact.html',{'msg':'added successfully'})

def order_details(request):
    try:
        pid=  int(request.GET['u'])
        product=Products.objects.get(id=pid)
        request.session['gt']=product.price
        
        customer=Customer.objects.get(id=request.session['customer'])
        return render(request,'common/order_details.html',{'customer':customer,'gtotal':product.price})
    except:
        # customer_details = Customer.objects.filter(id= request.session['customer']).values('customer_name','address','phone','email')
        # customer_name = customer_details[0]['customer_name']
        # phone  = customer_details[0]['phone']
        # email  = customer_details[0]['email']
        # address  = customer_details[0]['address']
        customer=Customer.objects.get(id=request.session['customer'])
        gtotal = request.session['gt']
        print("gt",gtotal)
        return render(request,'common/order_details.html',{'customer':customer,'gtotal':gtotal})

@login_required
def payment(request):

    name=Customer.objects.get(id=request.session['customer']).customer_name
    amount=request.session['gt']

    return render(request,'common/payment.html',{'name':name,'amount':amount})


@login_required

def order_payment(request):

    
    customer = request.session['customer']
    od=Order(customer_id=customer,amount=request.session['gt'],status='pending')
    od.save()
    request.session['oid']= od.id

   

    if request.method == "POST":
        customer = request.session['customer']
        amount = request.POST['total']
        
        print(amount)
        order_recipt="order_reciptid_11"
        notes={'shipping address':'bomalahalli,bangolre'}

        products= Order.objects.filter(customer_id=request.session['customer'],status='pending')

        client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

        payment = client.order.create(
            {"amount": float(amount) * 100, "currency": "INR", "payment_capture": "1",'notes':notes}
        )

        
        print(payment)



        request.session['oid']= od.id
        products=Cart.objects.filter(customer_id=customer) 


        for pro in products:

            print(pro.product_id)

            order=Order_detail(customer_id=customer,
                    productid_id=pro.product_id,
                    price=pro.product.price,
                    quantity=pro.qty,
                    status="order_pending",
                    payment_type="Razorpay",
                    order_id=od.id        
                    )
            order.save()
        products.delete()
        return JsonResponse(payment)

  
     

       



@login_required

def updatepayment(request):




    user_id=request.session['customer']
    Order.objects.filter(id=request.session['oid'],customer_id=user_id, status='pending').update(status="paid")
    pid=Order.objects.filter(id=request.session['oid'],customer_id=user_id, status='pending')
    print('hello')
    print(pid)
    customer_id=request.session['customer']
    products=Cart.objects.filter(customer_id=customer_id) 

    for pro in products:

        print(pro.product)

        order=Order_detail(customer_id=customer_id,
                    productid_id=pro.product,
                    price=pro.product.price,
                    quantity=pro.qty,
                    status="paid",
                    payment_type="Razorpay",
                    order_id= pid[0].id
        )
        order.save()
        products.delete()

    Order_detail.objects.filter(customer_id=user_id, status='order_pending',order_id=request.session['oid']).update(status='paid')
    return JsonResponse({'resp':'sucsses'})
  






def shop(request):
    error_msg =''

    products =Products.objects.all()


    if request.method == 'POST':

        pid = request.POST['pid']     #pid from hidden input tag
        customer = request.session['customer']



        record_exist = Cart.objects.filter( product = pid ,customer = customer ).exists()

        if not record_exist:


            cart = Cart(customer_id =customer ,product_id = pid )
            cart.save()
            return redirect('common:cart')

        else:

            error_msg = 'item is already in cart'



    return render(request,'common/shop.html',{'products':products,'error':error_msg})




def login(request):

    error_msg = ''

    if request.method == 'POST':

        email = request.POST['email']
        password = request.POST['password']

        try:
            customer = Customer.objects.get(email = email ,password = password)
            request.session['customer'] = customer.id
            return redirect('common:home')

        except:

            error_msg = 'email or password is incorrect'



    return render(request,'common/login.html',{'error_msg':error_msg})

def logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect('common:home')




def signup(request):

    success_msg =''
    error_msg =''


    if request.method == 'POST':
        cname = request.POST['customer_name']
        cphone = request.POST['phone']
        cemail = request.POST['email']
        cpassword = request.POST['password']
        caddress = request.POST['address']


        email_exist = Customer.objects.filter(email = cemail).exists()

        if not email_exist:

            customer = Customer(customer_name = cname ,phone = cphone , email = cemail ,password = cpassword, address =caddress)
            customer.save()
            success_msg = 'you registered successfully'

        else:

            error_msg = 'email is already exist'




    return render(request,'common/signup.html',{'success_message':success_msg,'error_message':error_msg})




@login_required
def change_password(request):

    success_msg = ''
    error_msg = ''


    if request.method == 'POST':

        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        confirm_pass = request.POST['confirm_password']

        if new_pass == confirm_pass :

            if len(new_pass) >= 8 :

                customer = Customer.objects.get(id = request.session['customer'])

                if customer.password == old_pass :

                    # customer.password = new_pass
                    # customer.save()

                    Customer.objects.filter(id = request.session['customer']).update( password = new_pass )

                    success_msg = 'password changed successfully'

                else:
                    error_msg = 'old password is incorrect'

            else:

                error_msg = 'passwords should be 8 characters'


        else:
            error_msg = 'passwords doesn\'t match'
    return render(request,'common/change_password.html',{'success_msg':success_msg,'error_msg':error_msg})



@login_required

def cart(request):

    cart = Cart.objects.filter(customer = request.session['customer']).annotate(total_price = F('product__price') * F('qty'))
    sum=0
    for i in cart:
        sum = sum + i.total_price
    
   
    request.session['gt']=sum


    return render(request,'common/cart.html',{'cart_items':cart,'Gtotal':sum})


def change_qty(request):
 
    quantity = int(request.POST['quantity'])
    p_id = request.POST['p_id']
    print(p_id,quantity)
    customer = Customer.objects.get(id = request.session['customer'])
   

    
    stock = Products.objects.get(id=p_id)
    print(stock.stock)

    if stock.stock > quantity:

        changeqty = Cart.objects.get(product_id=p_id,customer_id=request.session['customer'])
        print(changeqty.qty)
        changeqty.qty=quantity        #qty is from model cart
        changeqty.save()
        status=True
        cart2=Cart.objects.filter(product_id=p_id,customer_id=request.session['customer']).annotate(total_price = F('product__price') * F('qty')) #product__price is a method 
        sum=0
        for i in cart2:
            sum = sum + i.total_price
        print("hhhhh",sum)  
        request.session['gt']=sum  

        msg="qty update successfully"
    
        return JsonResponse({'data':sum ,'status':status})
    
    else:
        print(sum)
        status=False
        return JsonResponse({'status':status})


    
def product_detailes(request,pid):

    error_msg = ''
    qtys = 1

    product = Products.objects.get( id = pid )
    try:
        cartitems=Cart.objects.get(product_id=pid,customer_id = request.session['customer'])
        qtys=cartitems.qty
    except:
        pass    

    if request.method == 'POST':

        customer = request.session['customer']
        qty=request.POST['quantity']
        qty=int(qty)

        print(type(qty))

        record_exist = Cart.objects.filter( product = pid ,customer = customer ).exists()

ecommerce/common/templates/common/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title></title>
  <!-- bootstrap css link -->
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- icon link -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

  <!-- jquery cdn -->
  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
<!-- razorpay  -->
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <!-- css link -->
  {% block css %}
  <link rel="stylesheet" href="{% static '/css/base.css' %}">

  {% endblock css %}

  <style>
    .serch{
      position: absolute;
      background-color: white;
      width: 17%;
      text-align: center;
    }
    .serch div{
      border: 0.5px solid rgb(75, 66, 66);
      width: 100%;
    }
    .serch a{
      text-decoration: none;
    }
    .serch div:hover{
      color: white;
      background-color: brown;
    }
  </style>

</head>

<body id="ll">
  <!-- navbar -->
  <nav class="navbar navbar-expand-lg bg-light " id="navbar">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold fs-2" href="#"><span class="CHILL">CHILLAX</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-expanded="false">
        <span class="navbar-toggler-icon "><i class="bi bi-list"></i></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav fw-bold mx-auto" id="list">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'common:home' %}" style="color: brown;">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:about' %}" style="color: black;">About Us</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'common:shop' %}" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: black;">Products</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'common:readytocook' %}">READY TO COOK</a>
              <a class="dropdown-item" href="{% url 'common:heatandeat' %}">HEAT AND EAT</a>
              <a class="dropdown-item" href="{% url 'common:readytofry' %}">READY TO FRY</a>
            </div>
          </li>
      
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:contact' %}" style="color: black;">Contact Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'common:profile' %}" style="color: black;">Profile</a>
          </li>
          <li class="nav-item ms-5">
            <form class="d-flex" method="POST">
              {% csrf_token %}
              <input class="form-control me-2 " type="search" placeholder="Search product" aria-label="Search" id="searchdata" name="searchdata">
              <button class="btn btn-outline-dark" type="type" id="searchbtn" style="background-color: rgb(189, 68, 68);color: white;"><i class="bi bi-search"></i></button>
  
            </form>
            <div class="serch" id="search">

              <!-- search data come from database -->
            </div>     
          </li>
         
        </ul>
        <div class="ms-3">
         

          <a href="{% url 'common:cart' %}"  type=" button " class="btn"><i class="bi bi-cart-fill"></i></a>
         
         <a href="{% url 'common:login' %}" type="button" class="btn"><i class="bi bi-person-fill"></i></a>
         <a href="{% url 'common:logout' %}" type="button" class="btn text-danger"><i class="bi bi-box-arrow-right"></i></a>

          
        </div>
        </div>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock content %}

  <!-- footer part -->

  <footer class="bg-light pt-5 pb-3" id="footer">
    <div class="container text-center text-md-start">
      <div class="row ">
        <div class="col-lg-3 col-md-3 col-sm-6">
          <h5><span class="koko">Chillax</span></h5>
          <p>Chillax is a delicious new brand from the house of Frozen foods that’s committed to enhance your taste buds to the next level of yumminess with its wide range of ready to fry, ready to steam and ready to cook frozen food products.</p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
          <h5>PRODUCTS</h5>
          <p><a href=""></a>Ready To Cook</p>
          <p><a href=""></a>Ready To Fry</p>
          <p><a href=""></a>Heat And Eat</p>
          <p><a href=""></a>Poultry</p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
          <h5>LINKS</h5>
          <p><a href=""></a>Delivery</p>
          <p><a href=""></a>Returns</p>
          <p><a href=""></a>Privacy and policy</p>
          <p><a href=""></a>Terms & Conditions</p>

        </div>
        <div class="col-lg-3 col-md-3 col-sm-6">
          <h5>CONTACT</h5>
          <p><i class="bi bi-house-fill"></i> Calicut,kerala</p>
          <p><i class="bi bi-envelope-fill"></i>chillax@gmail.com</p>
          <p><i class="bi bi-phone-fill"></i>+91 9600050000</p>
          <p><i class="bi bi-printer-fill"></i>+33 2123215</p>

        </div>

      </div>
      <hr class="mb-4">
      <div class="row">
        <div class="col-lg-7 col-sm-12">
          <p>copyright 2020 reserved by:<strong>chillax </strong></p>
        </div>
        <div class="col-lg-4 col-sm-12">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i class="bi bi-facebook"></i></a></li>
            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i class="bi bi-whatsapp"></i></a></li>

            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i class="bi bi-twitter"></i></a></li>

            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i class="bi bi-linkedin"></i></a></li>

          </ul>
        </div>
      </div>
    </div>
  </footer>




  <!-- JavaScript Bundle with Popper -->

<script>
  $(document).ready(function(){
    $.ajaxSetup({
					headers: {
								  "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
								}
					})
          $(document).on('keyup','#searchdata',function(){

            var search_data = $('#searchdata').val()
            url='{% url "common:product_detailes" 0 %}'

            console.log(search_data)

            $.ajax({
                type: 'POST',
                url: "{% url 'common:search_product' %}",
                dataType :'json',
                data: {
                  'searchdata': search_data
                },


                success: function (response) {
                  console.log(response.results)
                  var datas=response.results
                  $('#search').empty();

                  for(i in datas){
                    var product=datas[i].product_name
                    var productid=datas[i].id
                    var uls=url.replace('0',productid)
                    console.log(product)
                    $('#search').append('<a href="'+uls+'"><div>'+product+'</div></a>')
                    

                  }
                  $('#searchdata').focusin(function(){
                    $('#search').empty()
                  })


                  

                  
                  

                }
          })
      })
    })
							

</script>
  <script rel="stylesheet" href="{% static '/bootstrap/bootstrap.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

</body>

</html>







    <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Products
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'common:readytocook' %}">READY TO COOK</a>
              <a class="dropdown-item" href="{% url 'common:heatandeat' %}">HEAT AND EAT</a>
              <a class="dropdown-item" href="{% url 'common:readytofry' %}">READY TO FRY</a>
            </div>
          </li> -->

ecommerce/common/templates/common/cart.html
{% extends 'common/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body onload="">
  {% csrf_token %}
  


  <table class="table bg-light">
    <thead>
      <tr>
        <th scope="col">sl.no.</th>
        <th scope="col">Product image</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">TotalPrice</th>
        <th scope="col"></th>

      </tr>
    </thead>
    <tbody>
      
   {% for product in cart_items %}

   <tr>

      <td>{{ forloop.counter }}</td>
      <td><img src="{{ product.product.image.url }}"  height="100px" alt=""></td>
      <td>{{ product.product.product_name }}</td>
      <td >₹ {{ product.product.price }}
        <input type="number" name="" value="{{product.product.price}}" id="price_{{product.product.id}}" hidden>

      </td>
      

      <td><input type="number" min="1" value="{{ product.qty }}" class="update-qty" max="" data-item ="{{ product.product.id }}"  id="qty_{{product.product.id}}" >
          <span id="out_{{product.product.id}}" ></span>
      
      </td>
      
      <td ><span id="total_{{product.product.id}}">₹{{product.total_price}}</span></td>

      <td><a href="{% url 'common:remove_cart' product.id %}" type="button" class="btn btn-danger">Remove</a></td>
     
      
</tr>

  {% endfor %}

  
</tbody>
</table>


<div style="margin-left: 500px;background-color: brown;">

<table class="table text-white" >


  <tr>
    <th>Grand Total </th>
    <td><span id="grand_total" style="font-weight: bolder;">Rs .{{Gtotal}}</span></td>
  </tr>

</table>

</div>
<div class="d-grid gap-2 col-4 ms-auto mb-5 me-5">
<a href="{% url 'common:order_details' %}" class="btn btn-dark" type="button">PROCEED TO CHECKOUT</a>
</div>




<script>
  $(document).ready(function(){
    $.ajaxSetup({
								headers: {
								  "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
								}
							  })
                $(document).on('change','.update-qty',function(){
							

							  
              var id = $(this).attr('data-item')

              var qty = $("#qty_"+id).val()

              var price = $('#price_'+id).val()

              console.log(id,qty ,price)

              $.ajax({
                type: 'POST',
                  url: "{% url 'common:change_qty' %}",
                  data: {
                'quantity': qty,
                'p_id' :id
                  },

                  success: function (response) {
                  console.log(response.status)

                  if(response.status == true)
                  
                  {
                    sub = 	qty * price
                  $('#total_'+id).text(sub)
                  $('#grand_total').text(response.data)
                  $('#out_'+id).text("")
                  }
                  
                  else if(response.status == false){

                    $('#out_'+id).css('color','red')
                    $('#out_'+id).text("out of stock")

                  }																	

                  // console.log(sub)
            
              }							
                
                })
                
              
              })


    


  })


  
  
  </script>
  

    

</body>
</html>



     







{% endblock%} 

ecommerce/common/templates/common/profile.html
{% extends 'common/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}




<div class="container mt-5">
    <div class="main-body  mt-5">

        <!-- Breadcrumb -->

        <!-- /Breadcrumb -->

        <div class="row gutters-sm">
            <div class="col-md-5 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="{% static '/images/demo.png' %}" alt="" class="rounded-circle" width="100">
                            <div class="mt-3">
                                <h1 style="color: brown;">Hello,{{customer_details.customer_name | upper }} </h1>
                                <!-- <p class="text-secondary mb-1">Full Stack Developer</p> -->
                                <!-- <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p> -->
                                <!-- <a href=""><button class="btn btn-primary">Edit</button></a> -->
                                
                                <!-- <button class="btn btn-outline-primary">Message</button> -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- edit  -->

                <div class="card mt-3">
                    <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <a href="{% url 'common:my_orders' %}" class="text-decoration-none fw-bold"><h4 class="mb-0">Your Orders</h4></a>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <a href="{% url 'common:change_password' %}"  class="text-decoration-none"> <h4 class="mb-0">Change Password</h4></a>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <a href="{% url 'common:shop' %}"  class="text-decoration-none"><h4 class="mb-0">Buy Again</h4></a>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <a href=""  class="text-decoration-none"> <h4 class="mb-0">Your Addresses</h4></a>
                            </li>
                        
                    </ul>
                </div>

                <!-- edit  -->


            </div>
            <div class="col-md-7">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Full Name</h6>
                            </div>
                            <div class="col-sm-9 text-dark fw-bold">
                               {{customer_details.customer_name | upper }} 
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{customer_details.email}}
                            </div>
                        </div>
                        <!-- <hr> -->
                        
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Mobile</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                               {{customer_details.phone}}
                            </div>
                        </div>
                        <hr>
                       
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                            {{customer_details.address}}
                            
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-12">
                                <a class="btn btn-warning " target="__blank" href="{% url 'common:edit_profile' %}">Edit</a> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>
{% endblock content%}