ecommerce/common/urls.py
from django.urls import path

from .import views

app_name='common'

urlpatterns = [
    path('',views.home,name='home'),
    path('about',views.about,name='about'),
    path('readytofry',views.readytofry,name='readytofry'),
    path('readytocook',views.readytocook,name='readytocook'),
    path('heatandeat',views.heatandeat,name='heatandeat'),
    path('contact',views.contact,name='contact'),
    path('shop',views.shop,name='shop'),
    path('login',views.login,name='login'),
    path('signup',views.signup,name='signup'),
    path('cart',views.cart,name='cart'),

    path('changepassword',views.change_password,name='change_password'),
    path('product/<int:pid>',views.product_detailes,name='product_detailes'),
    path('logout',views.logout,name='logout'),
    path('order_details',views.order_details,name='order_details'),
    path('payment',views.payment,name='payment'),

    path('mycart/remove/<int:c_id>',views.removecart,name='remove_cart'),
    path('change_qty',views.change_qty,name="change_qty"),
    path("order_payment", views.order_payment, name="orderpayment"),
    path("updatepayment", views.updatepayment, name="updatepayment"),
    path("profile", views.profile, name="profile"),
    path("edit_profile", views.edit_profile, name="edit_profile"),
    path("my_orders", views.my_orders, name="my_orders"),
    path("my_orders/cancel_order/<int:o_id>", views.cancel_order, name="cancel_order"),
    path("search_product", views.search_product, name="search_product"),

















    
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings







urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('adminsite/',include('ecommerceadmin.urls')),

    
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce/ecommerceadmin/urls.py
from django.urls import path

from .import views

app_name='ecommerceadmin'

urlpatterns = [
    path('home',views.index,name='adminhome'),
    path('',views.login,name='login'),
    path('catalogue',views.catalogue,name='catalogue'),
    path('addproduct',views.add_product,name='add_product'),
    path('updatestock',views.update_stock,name='update_stock'),
    path('orderhistory',views.order_history,name='order_history'),
    path('customers',views.customers,name='customers'),
    path('signup',views.signup,name='signup'),
    path('logout',views.logout,name='logout'),
    path('reviews',views.reviews,name='reviews'),
    path('change_password',views.change_password,name='change_password'),


    path('get_product',views.get_product,name='get_product'),
    path('product/delete_product/<int:pid>',views.delete_product,name='delete_product'),









]

ecommerce/ecommerceadmin/models.py
from django.db import models

# Create your models here.



class Admin(models.Model):
    admin_name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    phone = models.BigIntegerField()
    password = models.CharField(max_length=10)

    class Meta:
        db_table = 'admin'


class Products(models.Model):
    product_name = models.CharField(max_length=20)
    admin = models.ForeignKey(Admin,on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    stock = models.IntegerField()
    image = models.ImageField(upload_to = 'products/')
    price = models.FloatField()
    code = models.CharField(max_length=10)


    class Meta:
        db_table = 'product' 

ecommerce/ecommerceadmin/views.py
from django.shortcuts import render,redirect
from .models import Admin,Products
from common.models import Customer , Review ,Order_detail
from .decorators import login_required
from django.http import JsonResponse


# Create your views here.
@login_required

def index(request):

    admin = Admin.objects.filter(id= request.session['admin']).values('admin_name')
    admin_name = admin[0]['admin_name']

    product_count =Products.objects.all().count()
    order_count =Order_detail.objects.all().count()
    customers_count = Customer.objects.all().count()


    # orders=Order_detail.objects.all().order_by('date')

    orders=Order_detail.objects.all().order_by('-date')[0:4]


    return render(request,'ecommerceadmin/index.html',{'name':admin_name,'orders':orders,'p_count':product_count,'o_count':order_count,'c_count':customers_count})

def login(request):

    error_msg = ''

    if request.method == 'POST':

        email = request.POST['email']
        password = request.POST['password']

        try:
            admin = Admin.objects.get(email = email ,password = password)
            request.session['admin'] = admin.id
            return redirect('ecommerceadmin:adminhome')

        except:

            error_msg = 'email or password is incorrect'

    return render(request,'ecommerceadmin/login.html',{'error':error_msg})


@login_required

def add_product(request):

    success_msg = ''
    error_msg = ''

    if request.method == 'POST':

        product_name = request.POST['product_name']
        description = request.POST['description']
        price = request.POST['product_price']
        stock = request.POST['product_stock']
        code = request.POST['product_code']
        product_image = request.FILES['product_image']
        

        product_exist = Products.objects.filter(code = code ,admin = request.session['admin']).exists()  #it returns false or true

        if not product_exist:            

            product = Products(product_name = product_name , description = description , price = price , stock = stock , image = product_image , code = code , admin_id = request.session['admin'])
            product.save()
            success_msg ='product added successfully'

        else:

            error_msg = 'product is already added'

    return render(request,'ecommerceadmin/add_product.html',{'success':success_msg,'error':error_msg})



def update_stock(request):

    pno=Products.objects.all()

    if request.method=='POST':
        pid = request.POST['pno']
        n_stock = int(request.POST['n_stock'])
        newstock = Products.objects.get(id=pid)
        newstock.stock = n_stock
        newstock.save()


    return render(request,'ecommerceadmin/update_stock.html',{'pno':pno})

def reviews(request):

    reviews = Review.objects.all()

    return render(request,'ecommerceadmin/reviews.html',{'reviews':reviews})


@login_required

def catalogue(request):

    products = Products.objects.filter(admin = request.session['admin'])
    
    return render(request,'ecommerceadmin/catalogue.html',{'products':products})

def order_history(request):

    order_history=Order_detail.objects.all()

    return render(request,'ecommerceadmin/order_history.html',{'order_history':order_history})


@login_required

def change_password(request):

    error_msg = ''
    success_msg = ''

    if request.method == 'POST':

        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        confirm_pass = request.POST['confirm_password']

        if new_pass == confirm_pass :

            if len(new_pass) >= 8 :

                customer = Admin.objects.get(id = request.session['admin'])

                if customer.password == old_pass :

                    # customer.password = new_pass
                    # customer.save()

                    Admin.objects.filter(id = request.session['admin']).update( password = new_pass )
                    success_msg = 'password changed successfully'

                else:
                    error_msg = 'old password is incorrect'

            else:

                error_msg = 'passwords should be 8 characters'


        else:
            error_msg = 'passwords doesn\'t match'
    return render(request,'ecommerceadmin/change_password.html',{'success':success_msg,'error':error_msg})


@login_required

def customers(request):

    customer = Customer.objects.all()
    return render(request,'ecommerceadmin/customers.html',{'customer_list':customer})

def signup(request):

    success_msg =''
    error_msg =''


    if request.method == 'POST':
        aname = request.POST['admin_name']
        aphone = request.POST['phone']
        aemail = request.POST['email']
        apassword = request.POST['password']

        email_exist = Admin.objects.filter(email = aemail).exists()

        if not email_exist:

            admin = Admin(admin_name = aname ,phone = aphone , email = aemail ,password = apassword)
            admin.save()
            success_msg = 'you registered successfully'

        else:

            error_msg = 'email is already exist'

    return render(request,'ecommerceadmin/signup.html',{'error':error_msg,'success':success_msg})

def logout(request):
    del request.session['admin']
    request.session.flush()
    return redirect('ecommerceadmin:login')

def get_product(request):
    pid = request.POST['pid']
    p_no=Products.objects.get(id=pid)
    return JsonResponse({'data':p_no.stock})

def delete_product(request,pid):
    product =Products.objects.get(id=pid)
    product.delete()
    return redirect('ecommerceadmin:catalogue')

ecommerce/ecommerceadmin/templates/ecommerceadmin/add_product.html
{% extends 'ecommerceadmin/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<main class="">


    <!-- <div class="w3-container w3-teal bg-dark">
        <h2 class="text-white">ADD PRODUCT</h2>
    </div> -->
    <!-- <h1>jfsjkhjkgjkgjk</h1> -->
    <div class="w3-container w3-teal bg-dark mt-5">
        <h2 class="text-white" style="background-color: brown;">ADD PRODUCT</h2>
    </div>
    
      <h6 class="text-success text-center bg-white">{{ success }}</h6>
    
      <h6 class="text-danger text-center bg-white">{{ error }}</h6>
    
      <section style="height: 100%">
        <div class="container py-2" style="height: 100%">
          <div class="row d-flex justify-content-center align-items-center">
            <div class="col-md-8">
              <div
                class="card"
                style="border-radius: 1rem; height: 650px; width: 700px"
              >
                <div class="row g-0">
                  <div class="col-md-8 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                      <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
    
                        <!-- to error: add class "has-danger" -->
                        <div class="form-group">
                          <label for="Inputname">Product Name</label>
                          <input
                            type="text"
                            name="product_name"
                            class="form-control form-control-sm mt-3"
                            id="Inputname"
                          />
                        </div>
                        <div class="form-group">
                          <label for="Inputdescription">Description</label>
                          <textarea
                            name="description"
                            class="form-control form-control-sm mt-3"
                            id="Inputdescription"
                          ></textarea>
                        </div>
                        <!-- <div class="form-group">
                                                <label for="Inputcategory">Category</label>
                                                <input type="text" class="form-control form-control-sm mt-3" name="category" id="Inputcategory"></textarea>
                                            </div> -->
                        <div class="form-group">
                          <label for="Inputstock">Product stock</label>
                          <input
                            type="text"
                            class="form-control form-control-sm mt-3"
                            name="product_stock"
                            id="Inputstock"
                          />
                        </div>
                        <div class="form-group">
                          <label for="Inputprice">Product code</label>
                          <input
                            type="text"
                            class="form-control form-control-sm mt-3"
                            name="product_code"
                            id="Inputprice"
                          />
                        </div>
                        <div class="form-group">
                          <label for="Inputprice">Product Price</label>
                          <input
                            type="text"
                            class="form-control form-control-sm mt-3"
                            name="product_price"
                            id="Inputprice"
                          />
                        </div>
                        <div class="form-group mt-3">
                          <label for="Inputimage">Product Image</label>
                          <input
                            type="file"
                            id="file-ip-1"
                            name="product_image"
                            onchange="showPreview(event)"
                            class="form-control mt-3"
                          />
                        </div>
                        <button
                          type="submit"
                          class="btn btn-primary btn-block mt-5 text-center"
                        >
                          Submit
                        </button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>


    
</main>







{% endblock%} 

ecommerce/ecommerceadmin/templates/ecommerceadmin/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>admin</title>

  <!-- bootstrap cdn  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<!-- jquery cdn -->
  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>


</head>

<body>

  <!-- navbar part -->

    

  <nav class="navbar navbar-expand-lg bg-light " id="navbar">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold fs-2" href="#"><span class="koko">Chillax</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-expanded="false">
        <span class="navbar-toggler-icon "><i class="bi bi-list"></i></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav fw-bold mx-auto" id="list">
              <li class="nav-item">
                  <div class="list-group list-group-flush my-3">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:adminhome' %}" style="color: brown;"><i class="fas fa-tachometer-alt me-1 "></i>Dashboard</h5></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:add_product' %}" style="color: black;">Add Products</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:order_history' %}" style="color: black;">Order History</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:reviews' %}" style="color: black;">Reviews</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:update_stock' %}"  style="color: black;">Update Stock</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:catalogue' %}" style="color: black;">Catalogue</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:customers' %}" style="color: black;">Customers</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:change_password' %}" style="color: black;">Change Password</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ecommerceadmin:logout' %}" style="color: black;">Logout</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="" style="color: black;"></i>{{ name | upper }}</a>
                    </li>
                  
                  <!-- <li class="nav-item">
                <a class="nav-link active text-dark" aria-current="page" href=""><i class="fas fa-user me-2"></i>{{ name | upper }}</a>
              </li> -->
            </div>
              </li>
             
            </ul>
           
          </div>
        </div>
      </nav>
  <!-- offcanvas -->
      
    
      
      <!-- <div class="offcanvas offcanvas-start sidebar-nav bg-light" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div>
        <div class="offcanvas-header  ">
          <a href="{% url 'ecommerceadmin:adminhome' %}" class="text-decoration-none"><h5 class="offcanvas-title fw-bold mt-3" id="offcanvasExampleLabel" style="color: brown;"><i class="fas fa-tachometer-alt me-1 "></i>Dashboard</h5></a>
        </div>
        <div class="offcanvas-body">

          <div class="list-group list-group-flush my-3">
            
            <a href="{% url 'ecommerceadmin:add_product' %}" class="list-group-item list-group-item-action bg-transparent text-dark  fw-bold">
              <i class="fa-brands fa-shopify me-2"></i> Add Products
            </a>
            <a href="{% url 'ecommerceadmin:order_history' %}" class="list-group-item list-group-item-action bg-transparent text-dark  fw-bold">
              <i class="fas fa-folder-plus me-2"></i>Order History
            </a>
            <a href="{% url 'ecommerceadmin:reviews' %}" class="list-group-item list-group-item-action bg-transparent text-dark    fw-bold">
              <i class="fas fa-paperclip me-2"></i>Reviews
            </a>
            <a href="{% url 'ecommerceadmin:update_stock' %}" class="list-group-item list-group-item-action bg-transparent text-dark    fw-bold">
              <i class="fas fa-chart-line me-2"></i>Update Stock
            </a>
            <a href="{% url 'ecommerceadmin:catalogue' %}" class="list-group-item list-group-item-action bg-transparent text-dark    fw-bold">
              <i class="fas fa-shopping-cart me-2"></i>Catalogue
            </a>
            <a href="{% url 'ecommerceadmin:customers' %}" class="list-group-item list-group-item-action bg-transparent text-dark    fw-bold">
              <i class="fas fa-people-group me-2"></i>Customers
            </a>
            <a href="{% url 'ecommerceadmin:change_password' %}" class="list-group-item list-group-item-action bg-transparent text-dark    fw-bold">
              <i class="fas fa-gear me-2"></i>Change Password
            </a>
            <a href="{% url 'ecommerceadmin:logout' %}" class="list-group-item list-group-item-action bg-transparent text-danger  fw-bold">
              <i class="fa-brands fa-shopify me-2"></i>logout
            </a>
    
          </div>

          </div>
         
        </div>
      </div> -->

    <!-- content part -->

   {% block content %}
   {% endblock %}
    

      
     
   



  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>

</html>

ecommerce/ecommerceadmin/templates/ecommerceadmin/catalogue.html
{% extends 'ecommerceadmin/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<main class="mt-3 pt-3">

    
        <div class="w3-container w3-teal bg-dark">
          <h2 class="text-white" style="background-color: brown;">PRODUCT CATALOGUE</h2>
        </div>
      
      
      
          <div class="row pt-4 align-items-center gy-4  ">

      {% for product in products %}

            <div class="col-lg-3 col-md-6 col-sm-12 mx-sm-auto">
              <div class="card " style="width: 16rem;">
                <img class="card-img-top" src="{{ product.image.url }}" alt="nuts" height="330px">
                  <div class="card-body">
                    <h5 class="card-title">{{ product.product_name }}</h5>
                    <p class="card-text text-dark fw-bold">ID :{{ product.id }}</p>
                    <p class="card-text text-dark fw-bold">PRODUCT CODE:{{ product.code }}</p>

      
                    <p class="card-text text-warning">Rs .{{ product.price }}</p>
                    <p class="card-text text-info00">Description : {{ product.description }}</p>
                    <p class="card-text text-danger">Stock : {{ product.stock }}</p>
                    <a class="btn btn-danger mt-3" href="{% url 'ecommerceadmin:delete_product' product.id %}" type="button">Delete</a>

      
                  </div>  
              </div>
            </div>
      
        {% endfor %}
          </div>
        </div>
      
      
             
      
      



    
</main>







{% endblock%} 

ecommerce/ecommerceadmin/templates/ecommerceadmin/change_password.html
{% extends 'ecommerceadmin/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div style="margin-left:20%">
    <div class="w3-container w3-teal " style="background-color: brown;">
        <h2 class="text-white">CHANGE PASSWORD</h2>
      </div>

    <section class="vh-100">

      <h6 class="text-success text-center bg-white">{{ success }}</h6>
      <h6 class="text-danger text-center bg-white">{{ error }}</h6>


        
        <div class="container py-5" style="height:400px">
          <div class="row d-flex justify-content-center align-items-center">
             <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;height:450px;width:500px">
                 <div class="row g-0">
                   <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height:450px;" />
                  </div> 
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
      
                      <form method="POST">

                        {% csrf_token %}
      
      
                        <!-- to error: add class "has-danger" -->
                        <div class="form-group">
                          <label for="Inputpswd1">Old Password</label>
                          <input type="password" name="old_password" class="form-control form-control-sm mt-3" id="Inputoldpaswd"
                            aria-describedby="emailHelp">
                        </div>
                        <div class="form-group">
                          <label for="InputPswd2">New Password</label>
                          <input type="password"  name="new_password" class="form-control form-control-sm mt-3" id="Inputnewpassword">
                        </div>
                        <div class="form-group">
                            <label for="Inputpswd3">Confirm Password</label>
                            <input type="password"  name="confirm_password" class="form-control form-control-sm mt-3" id="Inputconfirmpassword">
                          </div>
                        <button type="submit" class="btn btn-primary btn-block mt-5">Submit</button>
      
                        
                      </form>
                    </div>
                  </div>
                </div>
               </div> 
             </div>
           </div> 
        </div>
      </section>





</div>






{% endblock%} 

ecommerce/ecommerceadmin/templates/ecommerceadmin/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>admin</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light " id="navbar">
      <div class="container-fluid">
        <a class="navbar-brand fw-bold fs-2" href="#"><span class="CHILL">Chillax</span></a>
        </div>
        </nav>
    <section class="login mb-5">
      <div class="row align-items-center"><h1 class="text-center" style="color: rgb(153, 232, 177); font-weight: bold;">ADMIN LOGIN</h1></div>
      <h6 class="text-danger text-center bg-white">
        {{ error }}
      </h6>
        <div class="container my-5 mx-5">
            <div class="row align-items-center shadow border-0 ">
                <div class="col-lg-5 col-12">
                    <img src="{% static '/image/CHILLAX (1).png' %}" alt="" class="img-fluid">
    
                </div>
                <div class="col-lg-7 col-12">
                    <form class="form" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}

                        <div class="mb-3">
                          <label for="exampleInputEmail1" class="form-label fw-bold">Email address</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                        </div>
                        <div class="mb-3">
                          <label for="exampleInputPassword1" class="form-label fw-bold">Password</label>
                          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                        </div>
                      
                      <button type="submit" class="btn btn-dark" >LogIn</button>
                        
                    </form><br>
          <p>Don't have an account?<a href="{% url 'ecommerceadmin:signup' %}" style="color: blue;" class="btn fw-bold">Create an account</a></p>

    
                </div>
            </div>
        </div>
    </section>




    <!-- Optional JavaScript -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

   
  </body>
</html>

ecommerce/ecommerceadmin/templates/ecommerceadmin/update_stock.html
{% extends 'ecommerceadmin/base.html' %}
{% load static %}



{% block content%}

<main class="mt-3 pt-3">


    
    <h1 style="text-align: center;font-weight: bolder;font-family: Georgia, 'Times New Roman', Times, serif;color: rgb(164, 204, 241);">
      UPDATE STOCK</h1><br>
    <form class="product-form form-inline" style="margin-left: 360px;" method="POST">
      {% csrf_token %}
    
      <table>
        
        <tr>
          <td><label for="exampleFormControlSelect1" class="lable m-3">Product No</label></td>
    
          <td> 
            <select class="form-control drop format  d-inline" id="p_no" name="pno">
              <option value="">select product</option>
                {% for i in pno %}
              <option value="{{i.id}}">{{i.product_name}}</option>

              {% endfor %}

            </select>
          </td>
        </tr>
        <tr>
          <td>
            <label for="exampleFormControlInput1" class="lable d-inline m-3">Current Stock</label>
    
          </td>
          <td>
            <input type="text" class="form-control  format d-inline" readonly id="c_stock" placeholder="" name="c_stock">
    
          </td>
        </tr>
        <tr>
          <td>
            <label for="exampleFormControlInput1" class="lable d-inline m-3">New Stock</label>
    
          </td>
          <td>
            <input type="text" class="form-control  format d-inline" id="n_stock" placeholder="" name="n_stock">
    
          </td>
        </tr>
    
        <tr>
          <td colspan="2" align="left">
    
            <button type="submit" class="btn btn-danger w-50 ml-4"
              style="position: relative;left:100px;top:20px;width: 100px">Update</button>
    
          </td>
          <td>
            {{msg}}
          </td>
        </tr>
      </table>
    </form>
    
    
  
    


    
</main>

<script>

$(document).ready(function () {
    $.ajaxSetup({
      headers: {
        "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
      }
    }) 

    $('#p_no').change(function () {

        var productid=$(this).val()


        $.ajax({
        type: 'POST',
        url: "{% url 'ecommerceadmin:get_product' %}",
        dataType:'json',
        data:{
            'pid':productid
        },
       

        success: function (response) { 
            console.log(response.data)

            $('#c_stock').val(response.data)


            
         
            
        }


        })

    })

    

})
</script>







{% endblock%} 